//export const server = "http://127.0.0.1:3000/api/"
export const server = "https://batshareapi.lumitylabs.com/api/"
export const endpoint_get_user = "get-user"
export const endpoint_get_projects = "get-projects"
export const endpoint_get_project = "get-project"
export const endpoint_create_user = "auth?action=create-user"
export const endpoint_get_project_raised = "get-project-raised"
export const endpoint_donate = "auth?action=donate"